version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    # Security updates will still come through despite ignores
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]