version: '3.8'
services:

  docs:
    build: .
    # command: bundle exec nanoc view --live-reload --port 8000 --host 0.0.0.0
    command: bundle exec nanoc live --port 8000 --host 0.0.0.0
    volumes:
      - .:/app
    environment:
      - NANOC_ENV=development
    ports:
      - "8000:8000"
      - "35729:35729"
