services:

  docs:
    build: .
    command: bash -c "bundle exec guard & bundle exec nanoc live --port 80 --host 0.0.0.0"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NANOC_ENV=development
    ports:
      - "8000:80"
      - "35729:35729"
